package com.lewis.base.mapper;

import com.lewis.base.entity.Cars;
import java.util.List;

public interface CarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int insert(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    Cars selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     * @param u_id
     */
    List<Cars> selectAll(Integer u_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cars record);

    Cars isExit(Cars cars);

    int delCar(Cars cars);
}